# Generated by Django 4.1.7 on 2024-06-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('tenth_marks', models.CharField(max_length=10)),
                ('twelfth_marks', models.CharField(max_length=10)),
                ('cgpa', models.CharField(max_length=5)),
                ('expected_salary', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
